## ANN (ARTIFICIAL NEURAL NETWORK)

### Rgression Modelling

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder,OneHotEncoder
import pickle

In [2]:
## Load the dataset
data=pd.read_csv("../Churn_Modelling.csv")

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.2 MB

In [5]:
## Preprocess the data
### Drop irrelevant columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

Note: Geography and Gender are categorical, which will require some kind of encoding

In [6]:
## Encode categorical variables (gender)
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
## OneHotEncoder for geography column

ohe=OneHotEncoder()
geo_encoder=ohe.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [8]:
encoded_columns=ohe.get_feature_names_out(['Geography'])
encoded_columns

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
## lets convert the encoded columns into pandas dataframe

geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=encoded_columns)

In [10]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [11]:
## combine columns with the original data
data=pd.concat([data.drop('Geography', axis=1),geo_encoded_df],axis=1)

data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
## Save the encoders and scalar
with open("label_encoder_gender.pkl",'wb') as file:
    pickle.dump(label_encoder_gender,file)

with open("onehot_encoder_geo.pkl", "wb") as file:
    pickle.dump(ohe,file)

In [13]:
## Divide the dataset into dependent and independent
X=data.drop("EstimatedSalary",axis=1)
y=data["EstimatedSalary"]

In [14]:
## Split the data to train and test
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
## scale the features
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [16]:
with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

In [17]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [18]:
### Training with regression

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [20]:
X_train_scaled.shape

(8000, 12)

In [21]:
X_train_scaled.shape[1] # To get the number of columns

12

In [22]:
## Build the ANN model
model=Sequential( ## sequential connects them all in a sequence
    [
        Dense(64,activation='relu',input_shape=(X_train_scaled.shape[1],)), ## First hidden layer(64 neurons) that is connected to the inputs
        Dense(32,activation='relu'), ## second hidden layer(32 neurons)
        Dense(1) ## output layer ### We wont apply any activation function because the default is 'linear' which is for regression problems
    ]  
)

c:\Users\pc\Downloads\python_deep_learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
# import tensorflow
# opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
# loss=tensorflow.keras.losses.MeanAbsoluteError

## We can directly input this but lets just follow KRISH

In [25]:
## Before we do the forward and backward propagation we need to COMPILE the model

model.compile(optimizer="adam",loss="mean_absolute_error",metrics=["mae"]) ## This initialization uses the generic 'adam' and 'binary_crossentropy'. You can initialize them like we did above to make our own adjustments and apply them as arguments

# model.compile(optimizer=opt,loss=loss,metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [26]:
## set up the tensor board
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="regressionlogs/fit"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [27]:
## setup early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10, restore_best_weights=True) ## This says monitor the training for validation loss(test set). If there is no improvement Be patient for at least 5 epochs.

In [28]:
## TRAINING THE MODEL
history=model.fit(
    X_train_scaled,y_train,validation_data=(X_test_scaled,y_test),epochs=100,callbacks=[early_stopping_callback,tensorboard_callback,]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - loss: 100353.1094 - mae: 100353.1094 - val_loss: 98430.6797 - val_mae: 98430.6797
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 99328.7891 - mae: 99328.7891 - val_loss: 96376.9688 - val_mae: 96376.9688
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 95768.2109 - mae: 95768.2109 - val_loss: 91202.8828 - val_mae: 91202.8828
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 88910.0859 - mae: 88910.0859 - val_loss: 82871.4844 - val_mae: 82871.4844
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 79406.9297 - mae: 79406.9297 - val_loss: 72999.7578 - val_mae: 72999.7578
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 69238.6094 - mae: 69238.6094 - val_loss: 63802.6758 - val_mae: 63802.6758
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 60589.0703 - mae: 60589.0703 - val_loss: 56898.1914 - val_mae: 56898.1914
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54893.3281 - mae: 54893.3281 - val_loss: 53174.4727 - val_mae: 53174.4727
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 52035.5664 - mae: 52035.5664 - val_loss: 51694.9102 - val_mae: 51694.9102
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 50933.9219 - mae: 50933.9219 - val_loss: 51293.0664 - val_mae: 51293.0664
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50577.8789 - mae: 50577.8789 - val_loss: 51176.6406 - val_mae: 51176.6406
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 50429.5859 - mae: 50429.5859 - val_loss: 51100.8203 - val_mae: 51100.8203
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50335.3281 - mae: 50335.3281 - val_loss: 51025.9102 - val_mae: 51025.9102
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 50264.2891 - mae: 50264.2891 - val_loss: 50978.7422 - val_mae: 50978.7422
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 50198.3789 - mae: 50198.3789 - val_loss: 50929.0234 - val_mae: 50929.0234
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 50142.8125 - mae: 50142.8125 - val_loss: 50885.9531 - val_mae: 50885.9531
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 50093.9492 - mae: 50093.9492 - val_loss: 50845.1523 - val_mae: 50845.1523
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 50045.0977 - mae: 50045.0977 - val_loss: 50804.8789 - val_mae: 50804.8789
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50001.6016 - mae: 50001.6016 - val_loss: 50765.1914 - val_mae: 50765.1914
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49966.1953 - mae: 49966.1953 - val_loss: 50725.8047 - val_mae: 50725.8047
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49931.8867 - mae: 49931.8867 - val_loss: 50700.1484 - val_mae: 50700.1484
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49901.2656 - mae: 49901.2656 - val_loss: 50676.6367 - val_mae: 50676.6367
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49874.3711 - mae: 49874.3711 - val_loss: 50652.0547 - val_mae: 50652.0547
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49844.3477 - mae: 49844.3477 - val_loss: 50639.0195 - val_mae: 50639.0195
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49817.1836 - mae: 49817.1836 - val_loss: 50624.2188 - val_mae: 50624.2188
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49792.6562 - mae: 49792.6562 - val_loss: 50599.5000 - val_mae: 50599.5000
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49773.6719 - mae: 49773.6719 - val_loss: 50582.9453 - val_mae: 50582.9453
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49751.7852 - mae: 49751.7852 - val_loss: 50572.4648 - val_mae: 50572.4648
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49734.1289 - mae: 49734.1289 - val_loss: 50562.5859 - val_mae: 50562.5859
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49712.0977 - mae: 49712.0977 - val_loss: 50552.3711 - val_mae: 50552.3711
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49696.8945 - mae: 49696.8945 - val_loss: 50534.2734 - val_mae: 50534.2734
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49681.7617 - mae: 49681.7617 - val_loss: 50525.8672 - val_mae: 50525.8672
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49663.9688 - mae: 49663.9688 - val_loss: 50512.2930 - val_mae: 50512.2930
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49649.5195 - mae: 49649.5195 - val_loss: 50505.0000 - val_mae: 50505.0000
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49636.5742 - mae: 49636.5742 - val_loss: 50492.1797 - val_mae: 50492.1797
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49624.6055 - mae: 49624.6055 - val_loss: 50477.5664 - val_mae: 50477.5664
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49610.0508 - mae: 49610.0508 - val_loss: 50467.0078 - val_mae: 50467.0078
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49598.8203 - mae: 49598.8203 - val_loss: 50470.0039 - val_mae: 50470.0039
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49589.2305 - mae: 49589.2305 - val_loss: 50469.1562 - val_mae: 50469.1562
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49576.2891 - mae: 49576.2891 - val_loss: 50460.4492 - val_mae: 50460.4492
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49563.1172 - mae: 49563.1172 - val_loss: 50460.5273 - val_mae: 50460.5273
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49555.8711 - mae: 49555.8711 - val_loss: 50461.7070 - val_mae: 50461.7070
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49545.2148 - mae: 49545.2148 - val_loss: 50447.1211 - val_mae: 50447.1211
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49533.7266 - mae: 49533.7266 - val_loss: 50455.7109 - val_mae: 50455.7109
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49521.8516 - mae: 49521.8516 - val_loss: 50443.9727 - val_mae: 50443.9727
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49518.4570 - mae: 49518.4570 - val_loss: 50445.8477 - val_mae: 50445.8477
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49508.0352 - mae: 49508.0352 - val_loss: 50436.5352 - val_mae: 50436.5352
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49499.8672 - mae: 49499.8672 - val_loss: 50447.8555 - val_mae: 50447.8555
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49492.0742 - mae: 49492.0742 - val_loss: 50426.9453 - val_mae: 50426.9453
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49482.8398 - mae: 49482.8398 - val_loss: 50450.5156 - val_mae: 50450.5156
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49476.1758 - mae: 49476.1758 - val_loss: 50435.8008 - val_mae: 50435.8008
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49466.5078 - mae: 49466.5078 - val_loss: 50441.7578 - val_mae: 50441.7578
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49461.8281 - mae: 49461.8281 - val_loss: 50448.7461 - val_mae: 50448.7461
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49451.5430 - mae: 49451.5430 - val_loss: 50460.9648 - val_mae: 50460.9648
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49442.6641 - mae: 49442.6641 - val_loss: 50453.3047 - val_mae: 50453.3047
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49441.5898 - mae: 49441.5898 - val_loss: 50456.9883 - val_mae: 50456.9883
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 49434.7695 - mae: 49434.7695 - val_loss: 50441.4688 - val_mae: 50441.4688
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49427.5664 - mae: 49427.5664 - val_loss: 50442.8164 - val_mae: 50442.8164
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49422.9570 - mae: 49422.9570 - val_loss: 50446.4727 - val_mae: 50446.4727

In [29]:
import os
os.environ["TENSORBOARD_BINARY"] = r"C:/Users/pc/Downloads/python_deep_learning/venv/Scripts/tensorboard.exe" ## We will have to manually assign the path to the TENSORBOARD_BINARY in the environment.

In [30]:
## Load Tensorboard Extension
%load_ext tensorboard

In [31]:
%tensorboard --logdir regressionlogs/fit20261008-155909

Reusing TensorBoard on port 6006 (pid 12196), started 2:19:20 ago. (Use '!kill 12196' to kill it.)

In [32]:
## Evaluate the model on the test data
test_loss,test_mae=model.evaluate(X_test_scaled,y_test)
print(f'Loss: {test_loss}, MAE:{test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50426.9453 - mae: 50426.9453
Loss: 50426.9453125, MAE:50426.9453125

In [33]:
## Save the model
model.save("regression_model.keras")

We will carryout deployment later. It follows the same process as we did with ann classification