## ANN (ARTIFICIAL NEURAL NETWORK)

### Churn Modelling

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder,OneHotEncoder
import pickle

In [2]:
## Load the dataset
data=pd.read_csv("../Churn_Modelling.csv")

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.2 MB

In [5]:
## Preprocess the data
### Drop irrelevant columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

Note: Geography and Gender are categorical, which will require some kind of encoding

In [6]:
## Encode categorical variables (gender)
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
## OneHotEncoder for geography column

ohe=OneHotEncoder()
geo_encoder=ohe.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [8]:
encoded_columns=ohe.get_feature_names_out(['Geography'])
encoded_columns

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
## lets convert the encoded columns into pandas dataframe

geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=encoded_columns)

In [10]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [11]:
## combine columns with the original data
data=pd.concat([data.drop('Geography', axis=1),geo_encoded_df],axis=1)

data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
## Save the encoders and scalar
with open("label_encoder_gender.pkl",'wb') as file:
    pickle.dump(label_encoder_gender,file)

with open("onehot_encoder_geo.pkl", "wb") as file:
    pickle.dump(ohe,file)

In [13]:
## Divide the dataset into dependent and independent
X=data.drop("Exited",axis=1)
y=data["Exited"]

In [14]:
## Split the data to train and test
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
## scale the features
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [16]:
with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

In [17]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [18]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [19]:
X_train_scaled.shape

(8000, 12)

In [20]:
X_train_scaled.shape[1] # To get the number of columns

12

In [21]:
## Build the ANN model
model=Sequential( ## sequential connects them all in a sequence
    [
        Dense(64,activation='relu',input_shape=(X_train_scaled.shape[1],)), ## First hidden layer(64 neurons) that is connected to the inputs
        Dense(32,activation='relu'), ## second hidden layer(32 neurons)
        Dense(1,activation='sigmoid') ## output layer
    ]  
)

c:\Users\pc\Downloads\python_deep_learning\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [24]:
## Before we do the forward and backward propagation we need to COMPILE the model

# model.compile(optimizer="adam",loss="binary_crossentropy",metric=["accuracy"]) ## This initialization uses the generic 'adam' and 'binary_crossentropy'. You can initialize them like we did above to make our own adjustments and apply them as arguments

model.compile(optimizer=opt,loss=loss,metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [25]:
## set up the tensor board
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [26]:
## setup early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=20, restore_best_weights=True) ## This says monitor the training for validation loss. If there is no improvement Be patient for at least 5 epochs.

In [27]:
## TRAINING THE MODEL
history=model.fit(
    X_train_scaled,y_train,validation_data=(X_test_scaled,y_test),epochs=100,callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.8359 - loss: 0.3965 - val_accuracy: 0.8615 - val_loss: 0.3503
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8541 - loss: 0.3564 - val_accuracy: 0.8620 - val_loss: 0.3432
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8580 - loss: 0.3496 - val_accuracy: 0.8560 - val_loss: 0.3528
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8587 - loss: 0.3441 - val_accuracy: 0.8585 - val_loss: 0.3431
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8604 - loss: 0.3450 - val_accuracy: 0.8555 - val_loss: 0.3604
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8591 - loss: 0.3400 - val_accuracy: 0.8615 - val_loss: 0.3406
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8610 - loss: 0.3366 - val_accuracy: 0.8610 - val_loss: 0.3471
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8635 - loss: 0.3361 - val_accuracy: 0.8610 - val_loss: 0.3408
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8640 - loss: 0.3314 - val_accuracy: 0.8550 - val_loss: 0.3499
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8634 - loss: 0.3278 - val_accuracy: 0.8625 - val_loss: 0.3476
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8673 - loss: 0.3287 - val_accuracy: 0.8490 - val_loss: 0.3603
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8674 - loss: 0.3238 - val_accuracy: 0.8605 - val_loss: 0.3443
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8650 - loss: 0.3238 - val_accuracy: 0.8575 - val_loss: 0.3556
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8684 - loss: 0.3207 - val_accuracy: 0.8575 - val_loss: 0.3401
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8692 - loss: 0.3180 - val_accuracy: 0.8605 - val_loss: 0.3480
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8714 - loss: 0.3118 - val_accuracy: 0.8625 - val_loss: 0.3469
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8727 - loss: 0.3112 - val_accuracy: 0.8635 - val_loss: 0.3504
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8750 - loss: 0.3036 - val_accuracy: 0.8675 - val_loss: 0.3486
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - accuracy: 0.8740 - loss: 0.3039 - val_accuracy: 0.8615 - val_loss: 0.3493
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8756 - loss: 0.3031 - val_accuracy: 0.8670 - val_loss: 0.3706
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8765 - loss: 0.3010 - val_accuracy: 0.8575 - val_loss: 0.3539
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8776 - loss: 0.2945 - val_accuracy: 0.8580 - val_loss: 0.3499
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8784 - loss: 0.2921 - val_accuracy: 0.8630 - val_loss: 0.3644
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8764 - loss: 0.2973 - val_accuracy: 0.8600 - val_loss: 0.3644
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8771 - loss: 0.2909 - val_accuracy: 0.8620 - val_loss: 0.3625
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8824 - loss: 0.2844 - val_accuracy: 0.8595 - val_loss: 0.3758
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8817 - loss: 0.2819 - val_accuracy: 0.8565 - val_loss: 0.3760
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8806 - loss: 0.2835 - val_accuracy: 0.8585 - val_loss: 0.3681
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8850 - loss: 0.2764 - val_accuracy: 0.8655 - val_loss: 0.3756
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8811 - loss: 0.2789 - val_accuracy: 0.8620 - val_loss: 0.3908
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8845 - loss: 0.2778 - val_accuracy: 0.8580 - val_loss: 0.3850
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8845 - loss: 0.2696 - val_accuracy: 0.8545 - val_loss: 0.4191
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8878 - loss: 0.2711 - val_accuracy: 0.8620 - val_loss: 0.3927
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8859 - loss: 0.2652 - val_accuracy: 0.8545 - val_loss: 0.4085

In [28]:
## save the model
model.save('model.keras') ## .h5 is compatible with tensorflow/keras

In [29]:
## Load Tensorboard Extension
%load_ext tensorboard

In [30]:
%tensorboard --logdir logs/fit20261007-110801/train/

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

There is an issue. Lets troubleshoot. We have to find out if the environment we are using contains tensorboard

In [31]:
import tensorboard
print(tensorboard.__version__)

2.21.0

In [32]:
import sys
print(sys.executable)

c:\Users\pc\Downloads\python_deep_learning\venv\python.exe

In [33]:
import os
os.environ["TENSORBOARD_BINARY"] = r"C:/Users/pc/Downloads/python_deep_learning/venv/Scripts/tensorboard.exe" ## We will have to manually assign the path to the TENSORBOARD_BINARY in the environment.

In [34]:
## Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [35]:
%tensorboard --logdir logs/fit20261007-110801

Reusing TensorBoard on port 6006 (pid 18124), started 1 day, 6:13:10 ago. (Use '!kill 18124' to kill it.)

We will carryout prediction in a different jupyter notebook. Note: It is not customary.